export const FETCH_TRENDING = "FETCH_TRENDING";
export const FETCH_NETFLIX_ORGINALS = "FETCH_NETFLIX_ORGINALS";
export const FETCH_TOP_RATED = "FETCH_TOP_RATED";
export const FETCH_ACTION = "FETCH_ACTION";
export const FETCH_COMEDY = "FETCH_COMEDY";
export const FETCH_ROMANCE = "FETCH_ROMANCE";
export const FETCH_DOCUMENTARIES = "FETCH_DOCUMENTARIES";
export const FETCH_HORROR = "FETCH_HORROR";
//
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const ADD_TO_MY_LIST = "ADD_TO_MY_LIST";
export const REMOVE_FROM_MY_LIST = "REMOVE_FROM_MY_LIST";
// FETCHING DETAILS
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_TV_DETAILS = "FETCH_TV_DETAILS";
export const SET_DETAILS_TO_NULL = "SET_DETAILS_TO_NULL";
// CREDITS
export const FETCH_TV_CREDITS = "FETCH_TV_CREDITS";
export const FETCH_MOVIE_CREDITS = "FETCH_MOVIE_CREDITS";
export const SET_CREDITS_TO_NULL = "SET_CREDITS_TO_NULL";
// SEASONS AND EPISODES
export const FETCH_SEASON_DETAIL = "FETCH_SEASON_DETAIL";
export const SET_SEASON_DETAIL_TO_NULL = "SET_SEASON_DETAIL_TO_NULL";
// SIMILAR
export const FETCH_SIMILAR_MOVIE = "FETCH_SIMILAR_MOVIE";
export const FETCH_SIMILAR_TV = "FETCH_SIMILAR_TV";
export const SET_SIMILAR_TO_NULL = "SET_SIMILAR_TO_NULL";
// GET VIDEOS
export const FETCH_MOVIE_VIDEOS = "FETCH_MOVIE_VIDEOS";
export const FETCH_TV_VIDEOS = "FETCH_TV_VIDEOS";
export const SET_VIDEOS_TO_NULL = "SET_VIDEOS_TO_NULL";
export const DELETE_FROM_MY_LIST = "DELETE_FROM_MY_LIST";
// GET TV SHOW BY GENRE
export const FETCH_TV_LATEST = "FETCH_TV_LATEST";
export const FETCH_TV_POPULAR = "FETCH_TV_POPULAR";
// 28 ACTION
export const FETCH_TV_ACTION = "FETCH_TV_ACTION";
export const FETCH_TV_COMEDY = "FETCH_TV_COMEDY";
export const FETCH_USER_MY_LIST = "FETCH_USER_MY_LIST";
export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";
